package dev.cxd.rat;

import dev.cxd.rat.commands.ListRolesCommand;
import dev.cxd.rat.commands.SetEnabledRoleCommand;
import dev.cxd.rat.config.RolesAmongTheTrainConfig;
import dev.cxd.rat.events.ModdedRoleAssigned;
import dev.cxd.rat.modded_murder.ModdedMurderGameMode;
import dev.cxd.rat.modded_murder.ModdedWeights;
import dev.cxd.rat.packet.SeerScanPacket;
import dev.doctor4t.trainmurdermystery.api.GameMode;
import dev.doctor4t.trainmurdermystery.api.Role;
import dev.doctor4t.trainmurdermystery.api.TMMGameModes;
import dev.doctor4t.trainmurdermystery.api.TMMRoles;
import dev.doctor4t.trainmurdermystery.cca.GameWorldComponent;
import dev.doctor4t.trainmurdermystery.client.gui.RoleAnnouncementTexts;
import dev.doctor4t.trainmurdermystery.command.ForceRoleCommand;
import dev.doctor4t.trainmurdermystery.event.AllowPlayerDeath;
import dev.doctor4t.trainmurdermystery.event.CanSeePoison;
import dev.doctor4t.trainmurdermystery.game.GameConstants;
import dev.doctor4t.trainmurdermystery.index.TMMItems;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.fabricmc.fabric.api.networking.v1.PayloadTypeRegistry;
import net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.entity.projectile.ProjectileUtil;
import net.minecraft.item.ItemStack;
import net.minecraft.server.network.ServerPlayerEntity;
import net.minecraft.sound.SoundCategory;
import net.minecraft.sound.SoundEvents;
import net.minecraft.text.Text;
import net.minecraft.util.Hand;
import net.minecraft.util.Identifier;
import net.minecraft.util.hit.EntityHitResult;
import net.minecraft.util.math.Box;
import net.minecraft.util.math.Vec3d;
import org.jetbrains.annotations.NotNull;

import java.util.*;

public class RolesAmongTheTrain implements ModInitializer {
    public static HashMap<Identifier, Integer> ROLE_MAX = new HashMap<>();

    public static HashMap<Role, List<UUID>> FORCED_MODDED_ROLE = new HashMap<>();
    public static HashMap<UUID, Role> FORCED_MODDED_ROLE_FLIP = new HashMap<>();

    public static ArrayList<Role> VANNILA_ROLES = new ArrayList<>();
    public static ArrayList<Role> SPECIAL_ROLES = new ArrayList<>();
    public static ArrayList<Role> OVERWRITE_ROLES = new ArrayList<>();
    public static String MOD_ID = "rat";

    public static GameMode MODDED_GAMEMODE;
    public static boolean wantsToStartVannila = false;

    public static HashMap<Role, RoleAnnouncementTexts.RoleAnnouncementText> autogeneratedAnnouncements = new HashMap<>();
    public static HashMap<RoleAnnouncementTexts.RoleAnnouncementText, Role> autogeneratedAnnouncements_flip = new HashMap<>();

    public static Role SEER = TMMRoles.registerRole(new Role(id("seer"), 0xC1713C, true, false, Role.MoodType.REAL, GameConstants.getInTicks(0, 10), false));
    public static Role TIMEKEEPER = TMMRoles.registerRole(new Role(id("time_keeper"), 0x0026FF, true, false, Role.MoodType.REAL, GameConstants.getInTicks(0, 10), true));
    public static Role APATHETIC = TMMRoles.registerRole(new Role(id("apathetic"), 0xC0C0C0, true, false, Role.MoodType.NONE, GameConstants.getInTicks(0, 10), false));
    public static Role TOXICOLOGIST = TMMRoles.registerRole(new Role(id("toxicologist"), 0xB8295A, true, false, Role.MoodType.NONE, GameConstants.getInTicks(0, 10), false));

    public static @NotNull Identifier id(String name) {
        return Identifier.of(MOD_ID, name);
    }

    @Override
    public void onInitialize() {

        RolesAmongTheTrainConfig.HANDLER.save();
        RolesAmongTheTrainConfig.HANDLER.load();

        VANNILA_ROLES.add(TMMRoles.LOOSE_END);
        VANNILA_ROLES.add(TMMRoles.CIVILIAN);
        VANNILA_ROLES.add(TMMRoles.KILLER);
        VANNILA_ROLES.add(TMMRoles.VIGILANTE);
        VANNILA_ROLES.add(TMMRoles.DISCOVERY_CIVILIAN);

        SPECIAL_ROLES.add(TMMRoles.LOOSE_END);
        SPECIAL_ROLES.add(TMMRoles.DISCOVERY_CIVILIAN);
        SPECIAL_ROLES.add(TMMRoles.CIVILIAN); // civilian is considered special since it can't be assigned, just given out to everyone

        OVERWRITE_ROLES.add(TMMRoles.CIVILIAN);
        OVERWRITE_ROLES.add(TMMRoles.KILLER);

        ModdedWeights.init();

        registerCommands();

        MODDED_GAMEMODE = TMMGameModes.registerGameMode(Identifier.of(MOD_ID, "modded"), new ModdedMurderGameMode(Identifier.of(MOD_ID, "modded")));
        refreshRoles();

        setRoleMaximum(SEER, 1);
        setRoleMaximum(TIMEKEEPER, 1);
        setRoleMaximum(APATHETIC, 1);
        setRoleMaximum(TOXICOLOGIST, 1);

        PayloadTypeRegistry.playC2S().register(SeerScanPacket.ID, SeerScanPacket.CODEC);

        ServerPlayNetworking.registerGlobalReceiver(SeerScanPacket.ID, (payload, context) -> {
            context.server().execute(() -> {
                ServerPlayerEntity player = context.player();
                UUID playerUUID = player.getUuid();

                // Check if player is Seer (or in creative mode)
                GameWorldComponent gameWorld = GameWorldComponent.KEY.get(player.getServerWorld());
                dev.doctor4t.trainmurdermystery.api.Role playerRole = gameWorld.getRole(player);
                boolean isCreative = player.isCreative();

                if (!isCreative && (playerRole == null || !playerRole.equals(SEER))) {
                    return;
                }

                // Check cooldown (skip for creative mode)
                if (!isCreative && !SeerCooldownManager.canUseAbility(playerUUID)) {
                    String timeLeft = SeerCooldownManager.getFormattedCooldown(playerUUID);
                    player.sendMessage(Text.literal("§cAbility on cooldown! Time remaining: " + timeLeft), true);
                    return;
                }

                // Find target player using raycast
                Vec3d start = player.getCameraPosVec(1.0F);
                Vec3d direction = player.getRotationVec(1.0F);
                Vec3d end = start.add(direction.multiply(20.0D));

                Box box = player.getBoundingBox().stretch(direction.multiply(20.0D)).expand(1.0D);

                EntityHitResult entityHitResult = ProjectileUtil.raycast(
                        player,
                        start,
                        end,
                        box,
                        (entity) -> !entity.isSpectator() && entity instanceof ServerPlayerEntity,
                        20.0D * 20.0D
                );

                if (entityHitResult != null && entityHitResult.getEntity() instanceof ServerPlayerEntity targetPlayer) {
                    // Get target's role
                    dev.doctor4t.trainmurdermystery.api.Role targetRole = gameWorld.getRole(targetPlayer);

                    if (targetRole != null) {
                        // Send message to Seer
                        player.sendMessage(
                                Text.literal("§e[Seer] §7" + targetPlayer.getName().getString() +
                                        " is a §r").append(Text.literal(targetRole.identifier().getPath())
                                        .styled(style -> style.withColor(targetRole.color()))),
                                true
                        );

                        // Play sound
                        player.playSoundToPlayer(SoundEvents.BLOCK_AMETHYST_BLOCK_BREAK, SoundCategory.MASTER, 1, 1);

                        // Set cooldown (skip for creative mode)
                        if (!isCreative) {
                            SeerCooldownManager.setOnCooldown(playerUUID);
                        }
                    } else {
                        // Target has no role (is civilian)
                        player.sendMessage(
                                Text.literal("§e[Seer] §7" + targetPlayer.getName().getString() +
                                        " is a §aPassenger"),
                                true
                        );
                        player.playSoundToPlayer(SoundEvents.BLOCK_AMETHYST_BLOCK_BREAK, SoundCategory.MASTER, 1, 1);
                        if (!isCreative) {
                            SeerCooldownManager.setOnCooldown(playerUUID);
                        }
                    }
                } else {
                    player.sendMessage(Text.literal("§cYou must be looking at a player!"), true);
                }
            });
        });

        CanSeePoison.EVENT.register((player)->{
            GameWorldComponent gameWorldComponent = (GameWorldComponent) GameWorldComponent.KEY.get(player.getWorld());
            if (gameWorldComponent.isRole((PlayerEntity) player, TOXICOLOGIST)) {
                return true;
            }
            return false;
        });

//        ModdedRoleAssigned.EVENT.register((player, role) -> {
//            if (role.equals(HOST)) {
//                player.giveItemStack(ModItems.MASTER_KEY.getDefaultStack());
//            }
//        });
    }

    public static void refreshRoles() {
        for (Role role : TMMRoles.ROLES) {
            if (SPECIAL_ROLES.contains(role)) continue;
            if (!ModdedWeights.roleRounds.containsKey(role)) {
                ModdedWeights.roleRounds.put(role, new HashMap<>());
                ModdedWeights.roleWeights.put(role, new HashMap<>());

                RoleAnnouncementTexts.RoleAnnouncementText roleAnnouncementText = new RoleAnnouncementTexts.RoleAnnouncementText(role.identifier().getPath(),role.color());
                autogeneratedAnnouncements.put(role, roleAnnouncementText);
                autogeneratedAnnouncements_flip.put(roleAnnouncementText, role);
                RoleAnnouncementTexts.registerRoleAnnouncementText(roleAnnouncementText);
            }
        }
    }

    public static void addToForcedRoles(Role role, PlayerEntity player) {
        if (!FORCED_MODDED_ROLE.containsKey(role)) FORCED_MODDED_ROLE.put(role, new ArrayList<>());
        FORCED_MODDED_ROLE.get(role).add(player.getUuid());

        FORCED_MODDED_ROLE_FLIP.put(player.getUuid(), role);
    }

    public static void setRoleMaximum(Identifier role, Integer max) {
        ROLE_MAX.put(role,max);
    }
    public static void setRoleMaximum(Role role, Integer max) {
        setRoleMaximum(role.identifier(),max);
    }
    public void registerCommands() {
        CommandRegistrationCallback.EVENT.register((dispatcher, registryAccess, environment) -> {
            ForceRoleCommand.register(dispatcher);
            SetEnabledRoleCommand.register(dispatcher);
            ListRolesCommand.register(dispatcher);
        });
    }
}